// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/remcap.proto

package remcappb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Packet struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Packet) Reset()         { *m = Packet{} }
func (m *Packet) String() string { return proto.CompactTextString(m) }
func (*Packet) ProtoMessage()    {}
func (*Packet) Descriptor() ([]byte, []int) {
	return fileDescriptor_ddff1734508bac4b, []int{0}
}

func (m *Packet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Packet.Unmarshal(m, b)
}
func (m *Packet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Packet.Marshal(b, m, deterministic)
}
func (m *Packet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Packet.Merge(m, src)
}
func (m *Packet) XXX_Size() int {
	return xxx_messageInfo_Packet.Size(m)
}
func (m *Packet) XXX_DiscardUnknown() {
	xxx_messageInfo_Packet.DiscardUnknown(m)
}

var xxx_messageInfo_Packet proto.InternalMessageInfo

func (m *Packet) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Summary struct {
	StartTime            int64    `protobuf:"varint,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              int64    `protobuf:"varint,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	PacketsCaptured      int64    `protobuf:"varint,3,opt,name=packets_captured,json=packetsCaptured,proto3" json:"packets_captured,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Summary) Reset()         { *m = Summary{} }
func (m *Summary) String() string { return proto.CompactTextString(m) }
func (*Summary) ProtoMessage()    {}
func (*Summary) Descriptor() ([]byte, []int) {
	return fileDescriptor_ddff1734508bac4b, []int{1}
}

func (m *Summary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Summary.Unmarshal(m, b)
}
func (m *Summary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Summary.Marshal(b, m, deterministic)
}
func (m *Summary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Summary.Merge(m, src)
}
func (m *Summary) XXX_Size() int {
	return xxx_messageInfo_Summary.Size(m)
}
func (m *Summary) XXX_DiscardUnknown() {
	xxx_messageInfo_Summary.DiscardUnknown(m)
}

var xxx_messageInfo_Summary proto.InternalMessageInfo

func (m *Summary) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *Summary) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *Summary) GetPacketsCaptured() int64 {
	if m != nil {
		return m.PacketsCaptured
	}
	return 0
}

func init() {
	proto.RegisterType((*Packet)(nil), "remcap.Packet")
	proto.RegisterType((*Summary)(nil), "remcap.Summary")
}

func init() { proto.RegisterFile("proto/remcap.proto", fileDescriptor_ddff1734508bac4b) }

var fileDescriptor_ddff1734508bac4b = []byte{
	// 195 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x8f, 0x41, 0x4a, 0xc6, 0x30,
	0x10, 0x85, 0xa9, 0xbf, 0xa6, 0x75, 0x10, 0x2b, 0xb3, 0xaa, 0xa2, 0x20, 0x5d, 0x55, 0x17, 0x15,
	0xd4, 0x13, 0xd8, 0x0b, 0x48, 0xeb, 0xca, 0x4d, 0x99, 0x36, 0x53, 0x28, 0x92, 0x34, 0xa4, 0xe9,
	0xc2, 0xdb, 0x0b, 0x93, 0xb8, 0xcb, 0xfb, 0xde, 0x83, 0x7c, 0x03, 0xe8, 0xfc, 0x16, 0xb6, 0x17,
	0xcf, 0x66, 0x26, 0xd7, 0x4a, 0x40, 0x15, 0x53, 0x7d, 0x0f, 0xea, 0x93, 0xe6, 0x1f, 0x0e, 0x88,
	0x70, 0xae, 0x29, 0x50, 0x95, 0x3d, 0x66, 0xcd, 0x55, 0x2f, 0xef, 0xda, 0x42, 0x3e, 0x1c, 0xc6,
	0x90, 0xff, 0xc5, 0x07, 0x80, 0x3d, 0x90, 0x0f, 0x63, 0x58, 0x0d, 0xcb, 0xe8, 0xd4, 0x5f, 0x0a,
	0xf9, 0x5a, 0x0d, 0xe3, 0x2d, 0x14, 0x6c, 0x75, 0x2c, 0xcf, 0xa4, 0xcc, 0xd9, 0x6a, 0xa9, 0x9e,
	0xe0, 0xc6, 0xc9, 0x17, 0xfb, 0x38, 0x93, 0x0b, 0x87, 0x67, 0x5d, 0x9d, 0x64, 0x52, 0x26, 0xde,
	0x25, 0xfc, 0xfa, 0x0e, 0xaa, 0x67, 0xd3, 0x91, 0xc3, 0x67, 0xb8, 0x18, 0xec, 0xba, 0x2c, 0x78,
	0xdd, 0x26, 0xef, 0xa8, 0x79, 0x57, 0xfe, 0xe7, 0x24, 0xd6, 0x64, 0x1f, 0xf0, 0x5d, 0x44, 0xe6,
	0xa6, 0x49, 0xc9, 0x79, 0x6f, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x9e, 0xf1, 0x6c, 0x80, 0xf4,
	0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RemCapClient is the client API for RemCap service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RemCapClient interface {
	Sniff(ctx context.Context, opts ...grpc.CallOption) (RemCap_SniffClient, error)
}

type remCapClient struct {
	cc *grpc.ClientConn
}

func NewRemCapClient(cc *grpc.ClientConn) RemCapClient {
	return &remCapClient{cc}
}

func (c *remCapClient) Sniff(ctx context.Context, opts ...grpc.CallOption) (RemCap_SniffClient, error) {
	stream, err := c.cc.NewStream(ctx, &_RemCap_serviceDesc.Streams[0], "/remcap.RemCap/Sniff", opts...)
	if err != nil {
		return nil, err
	}
	x := &remCapSniffClient{stream}
	return x, nil
}

type RemCap_SniffClient interface {
	Send(*Packet) error
	CloseAndRecv() (*Summary, error)
	grpc.ClientStream
}

type remCapSniffClient struct {
	grpc.ClientStream
}

func (x *remCapSniffClient) Send(m *Packet) error {
	return x.ClientStream.SendMsg(m)
}

func (x *remCapSniffClient) CloseAndRecv() (*Summary, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Summary)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RemCapServer is the server API for RemCap service.
type RemCapServer interface {
	Sniff(RemCap_SniffServer) error
}

// UnimplementedRemCapServer can be embedded to have forward compatible implementations.
type UnimplementedRemCapServer struct {
}

func (*UnimplementedRemCapServer) Sniff(srv RemCap_SniffServer) error {
	return status.Errorf(codes.Unimplemented, "method Sniff not implemented")
}

func RegisterRemCapServer(s *grpc.Server, srv RemCapServer) {
	s.RegisterService(&_RemCap_serviceDesc, srv)
}

func _RemCap_Sniff_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RemCapServer).Sniff(&remCapSniffServer{stream})
}

type RemCap_SniffServer interface {
	SendAndClose(*Summary) error
	Recv() (*Packet, error)
	grpc.ServerStream
}

type remCapSniffServer struct {
	grpc.ServerStream
}

func (x *remCapSniffServer) SendAndClose(m *Summary) error {
	return x.ServerStream.SendMsg(m)
}

func (x *remCapSniffServer) Recv() (*Packet, error) {
	m := new(Packet)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _RemCap_serviceDesc = grpc.ServiceDesc{
	ServiceName: "remcap.RemCap",
	HandlerType: (*RemCapServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Sniff",
			Handler:       _RemCap_Sniff_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/remcap.proto",
}
